export const MutationTypes = {
  SET_ALL_PRODUCTS: "SET_ALL_PRODUCTS",
  SET_ALL_PRODUCTS_STATUS: "SET_ALL_PRODUCTS_STATUS",
  SET_NAMES: "SET_NAMES",
  SET_NAMES_STATUS: "SET_NAMES_STATUS",
  ADD_PRODUCT_TO_CART: "ADD_PRODUCT_TO_CART",
  REMOVE_PRODUCT_FROM_CART: "REMOVE_PRODUCT_FROM_CART"
};
